apiVersion: apps/v1
kind: Deployment
metadata:
  name: analitika-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analitika
  template:
    metadata:
      labels:
        app: analitika
    spec:
      containers:
        - image: rso2223s01/analitika:latest
          name: analitika
          env:
            - name: KUMULUZEE_SERVER_CONTEXTPATH
              value: /analytics
            - name: KUMULUZEE_HEALTH_CHECKS_HTTPHEALTHCHECK0_CONNECTIONURL
              value: http://localhost:8080/analytics/openapi
            - name: KUMULUZEE_CONFIG_CONSUL_AGENT
              value: http://consul:8500
            - name: INTEGRATIONS_NAROCILA_BASEURL
              value: http://narocila:8080/orders/graphql
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /analytics/health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /analytics/health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: analitika
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: analitika
